unit TestUProduto;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UProduto;

type
  // Test methods for class TProduto

  TestTProduto = class(TTestCase)
  strict private
    FProduto: TProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRetornarValorTotal;
  end;

implementation

procedure TestTProduto.SetUp;
begin
  FProduto := TProduto.Create;
end;

procedure TestTProduto.TearDown;
begin
  FProduto.Free;
  FProduto := nil;
end;

procedure TestTProduto.TestRetornarValorTotal;
var
  ReturnValue: Double;
begin
  FProduto := TProduto.Create;
  FProduto.NomeProduto := 'Caixa';
  FProduto.Quantidade := 10;
  FProduto.PrecoUnitario := 10.00;
  ReturnValue := FProduto.RetornarValorTotal(FProduto.Quantidade,
                                             FProduto.PrecoUnitario);
  CheckEquals(100, ReturnValue, 'Erro no método RetornarValorToral');

  FProduto.Quantidade := 11;
  ReturnValue := FProduto.RetornarValorTotal(FProduto.Quantidade,
                                             FProduto.PrecoUnitario);
  CheckEquals(99,9, ReturnValue, 'Erro no método RetornarValorToral');

  FProduto.Quantidade := 51;
  ReturnValue := FProduto.RetornarValorTotal(FProduto.Quantidade,
                                             FProduto.PrecoUnitario);
  CheckEquals(382.5, ReturnValue, 'Erro no método RetornarValorToral')
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProduto.Suite);
end.

